import './globals.css'
import { Inter } from 'next/font/google'

// components
import Header from '@/components/Header'
import Footer from '@/components/Footer'

// theme provider
import { ThemeProvider } from '@/components/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Nirmala's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
        <Header/>
        {children}
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  )
}
